# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 文件路径 示例（ Windows配置 D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  #profile: /data/wwwroot/erp.ysxinyi.com/server/ruoyi/upload
  profile: /data/wwwroot/erp/server/storage
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2801388jessieHm
    url: jdbc:mysql://127.0.0.1:3306/mes?autoReconnect=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    hikari:
      connection-timeout: 30000  #请求连接的超时时间
      maximum-pool-size: 10     #最大连接数量
      idle-timeout: 600000
      max-lifetime: 1800000    #连接的最长生命周期
      minimum-idle: 5
      connection-test-query: select 1
  #数据源的其他配置
  data:
    redis:
      # 地址
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      #password:
      # 连接超时时间
      connect-timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms