# Spring配置
spring:
  messages:
    basename: i18n/messages
    cache-duration: 3600
    fallback-to-system-locale: true
    encoding: UTF-8
  profiles:
    active: dev
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8060
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: utf-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    org.springframework: warn
    org.springframework.security: error

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10
    # 默认密码
    defaultPassword: 123456789

# MyBatis配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    #驼峰
    map-underscore-to-camel-case: true
    #全局性延迟加载
    lazy-loading-enabled: true
    #开启立即加载，否则按需加载
    aggressive-lazy-loading: false
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  type-aliases-package: com.ruoyi.**.domain.entity

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALJvyfexos1ifL4UStyUE8D8zwXDeX8CN3PZi/pNYgh3RexJRwQJ1g+Mab706lC9tV4pPGAejmidrHSiTcilB8sCAwEAAQ==
  # 访问令牌有效期（默认1天）
  expireTime: 1440
  #刷新停牌有效期（默认7天）
  refreshTime: 10080


# PageHelper分页插件
pagehelper:
  # 设置方言，此处指定 MySQL 数据库
  helper-dialect: mysql
  # 是否启动合理化，默认是 false。
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages（最大页数）会查询最后一页。
  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 是否支持接口参数来传递分页参数，默认false
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: count=countSql
  # 默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
  page-size-zero: true



